Fix idlcxx_generate, make assert in alignment conditional and finish up unions
eclipse-cyclonedds/cyclonedds-cxx pull request #71
Opened 2021-05-04 15:45 UTC by k0ekk0ek

* `idlcxx_generate` didn't add a dependency on the right target causing parallel Windows builds, like our CI builds, to fail.
* Aparently the cursor is always NULL in alignment of the CDR stream initially, or at least, it depends on the `add_zeroes` parameter. This PR corrects that.
* Union support depended on something not yet available in the IDL tree structure, namely the number of unused labels. [PR 784](https://github.com/eclipse-cyclonedds/cyclonedds/pull/784) in the *cyclonedds* repository fixes that. (until that one is merged, this PR will fail to build).

2021-05-06 13:32 UTC, k0ekk0ek commented
Did some basic manual testing with unions in the Hello World example and publishing at least seems to work. I have to carry out a couple more tests, but this is mostly done.

2021-05-07 08:47 UTC, reicheratwork requested changes
One thing that i thought was missing after looking at the generated code, is that for the generated function "max" does not give the correct end result for unions:

after all the possible branches have been gone over the stream position and alignment need to be set to the value that they had with the case which gave the largest stream position

2021-05-07 08:47 UTC, reicheratwork commented on src/idlcxx/src/streamers.c
>    static const char writefmt[] =
maybe replace writefmt and movefmt with:
    "      %s(str, instance.%s());\n"
    "      break;\n";

and then in the print add "write" for the write stream and "move" for the move stream?

2021-05-07 08:47 UTC, reicheratwork commented on src/idlcxx/src/streamers.c
>      "  size_t union_max = str.position();\n";
also create a holder for the "largest case" alignment
replace with "size_t union_max = str.position(), alignment_max = str.alignment();\n";

2021-05-07 08:47 UTC, reicheratwork commented on src/idlcxx/src/streamers.c
> +    "    union_max = std::max(str.position(),union_max);\n"
we also need to store the alignment in this case, so replace with:

"if (union_max > str.position()) {\n"
"  union_max = str.position();\n"
"  alignment_max = str.alignment();\n"
"}\n"

2021-05-10 07:53 UTC, k0ekk0ek commented
Build fails due to cyclonedds [#791](https://github.com/eclipse-cyclonedds/cyclonedds/pull/791) hasn't been merged yet.

2021-05-10 09:38 UTC, reicheratwork commented on src/idlcxx/src/streamers.c
> +    "    union_max = std::max(str.position(),union_max);\n"
My apologies, the larger than sign should have been a smaller than sign, as union_max needs to be "pushed forward" if a larger value is encountered, not the other way around.

2021-05-10 09:52 UTC, reicheratwork requested changes
I approve these changes, if the the comparison operator in streamers.c:171 is changed.

2021-05-10 09:52 UTC, reicheratwork commented on src/idlcxx/src/streamers.c
> +    "    if (union_max > str.position()) {\n"
Should be `union_max > str.position()` since we want to select the largest, not the smallest.

2021-05-10 12:01 UTC, k0ekk0ek commented
Thanks @reicheratwork! Your comments have been processed :+1:

2021-05-10 12:01 UTC, merged