Fix for cyclonedds-cxx/idlcxx issue #70
eclipse-cyclonedds/cyclonedds-cxx pull request #74
Opened 2021-05-07 11:54 UTC by reicheratwork

Multiple deserialization is prevented by:
- adding a parameter to the getT() function which indicates
whether the sample which is returned should deserialize the
raw data in the structure
- adding an internal parameter which keeps track of whether
the sample returned by the getT() function contains deserialized
data

@sumanth-nirmal @e-hndrks : could you check whether this works as expected and that I did not forget anything?

2021-05-07 14:26 UTC, sumanth-nirmal requested changes

2021-05-11 09:26 UTC, reicheratwork commented
Improved the implementation by splitting out a separate setter function `setT` which does not do unnecessary deserializations.

@sumanth-nirmal could you check this?

2021-05-12 04:30 UTC, sumanth-nirmal commented on src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
> +    return t;
We don't need to return anything, correct?

2021-05-12 13:34 UTC, reicheratwork commented
@sumanth-nirmal The function could just as well return void, but as this function changes the contents of the entity, I think it is a good habit to return the thing that has changed (in this case the pointer of the contained sample).
Also the symmetry with the getT() function also returning the pointer to the sample is another reason why I thought that returning the sample pointer is a good idea.

2021-05-12 15:55 UTC, sumanth-nirmal commented
@reicheratwork I would agree. The changes look good from me. @e-hndrks Can you probably also glance over?

2021-05-12 15:56 UTC, sumanth-nirmal approved these changes

2021-05-17 08:47 UTC, k0ekk0ek commented
Included in #79 as well.

2021-05-17 08:49 UTC, merged